export const products = [
  {
    id: 1,
    name: "Minimalist Leather Watch",
    category: "Accessories",
    price: 249,
    originalPrice: 320,
    rating: 4.8,
    reviews: 312,
    badge: "Sale",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80",
    description: "A refined timepiece crafted from genuine leather with a Swiss quartz movement. Perfect for the modern professional who values understated elegance.",
    features: ["Swiss Quartz Movement", "Genuine Italian Leather Band", "Sapphire Crystal Glass", "Water Resistant 50m", "2-Year Warranty"],
  },
  {
    id: 2,
    name: "Wireless Noise-Cancelling Headphones",
    category: "Electronics",
    price: 379,
    originalPrice: null,
    rating: 4.9,
    reviews: 1024,
    badge: "Hot",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80",
    description: "Industry-leading noise cancellation with 30-hour battery life. Experience music the way it was meant to be heard.",
    features: ["Active Noise Cancellation", "30hr Battery Life", "Multipoint Bluetooth 5.2", "Premium Carry Case Included", "Hi-Res Audio Certified"],
  },
  {
    id: 3,
    name: "Ceramic Pour-Over Coffee Set",
    category: "Home & Kitchen",
    price: 89,
    originalPrice: 120,
    rating: 4.7,
    reviews: 238,
    badge: "Sale",
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80",
    description: "Hand-thrown ceramic pour-over set with matching mug. Elevate your morning ritual with this beautifully crafted collection.",
    features: ["Hand-Thrown Ceramic", "Dishwasher Safe", "Includes Filter & Mug", "Capacity: 600ml", "Matte Glaze Finish"],
  },
  {
    id: 4,
    name: "Merino Wool Crewneck Sweater",
    category: "Clothing",
    price: 145,
    originalPrice: null,
    rating: 4.6,
    reviews: 189,
    badge: "New",
    image: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&q=80",
    description: "Luxuriously soft 100% merino wool sweater. Temperature-regulating and naturally odor-resistant for year-round comfort.",
    features: ["100% Merino Wool", "Temperature Regulating", "Machine Washable", "Available in 8 Colors", "Ethically Sourced"],
  },
  {
    id: 5,
    name: "Portable Bluetooth Speaker",
    category: "Electronics",
    price: 129,
    originalPrice: 159,
    rating: 4.5,
    reviews: 567,
    badge: "Sale",
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&q=80",
    description: "360° surround sound in a compact, waterproof design. Take your music anywhere with 24-hour playtime.",
    features: ["360° Sound", "IPX7 Waterproof", "24hr Battery", "USB-C Fast Charging", "Built-in Microphone"],
  },
  {
    id: 6,
    name: "Artisan Scented Candle Set",
    category: "Home & Kitchen",
    price: 58,
    originalPrice: null,
    rating: 4.8,
    reviews: 421,
    badge: "New",
    image: "https://api.floraindia.com/upload/9s0hTk0zKf1736144064736.webp",
    description: "Three hand-poured soy wax candles in signature scents: Cedarwood & Amber, Sea Salt & Driftwood, Bergamot & Sandalwood.",
    features: ["100% Soy Wax", "60hr Burn Time Each", "Lead-Free Cotton Wicks", "Reusable Glass Vessels", "Gift Box Included"],
  },
  {
    id: 7,
    name: "Slim Leather Cardholder",
    category: "Accessories",
    price: 65,
    originalPrice: null,
    rating: 4.7,
    reviews: 156,
    badge: null,
    image: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&q=80",
    description: "Ultra-slim full-grain leather cardholder that fits up to 8 cards. Designed to slide effortlessly into your front pocket.",
    features: ["Full-Grain Leather", "Holds 8 Cards", "RFID Blocking", "1 Bill Compartment", "Slim Profile (5mm)"],
  },
  {
    id: 8,
    name: "Premium Yoga Mat",
    category: "Sports",
    price: 98,
    originalPrice: 130,
    rating: 4.9,
    reviews: 743,
    badge: "Hot",
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&q=80",
    description: "Eco-friendly natural rubber yoga mat with alignment lines. Non-slip surface for stability and precision in every pose.",
    features: ["Natural Rubber", "6mm Thickness", "Alignment Lines", "Carrying Strap Included", "Eco-Certified"],
  },
  {
    id: 9,
    name: "Stainless Steel Water Bottle",
    category: "Sports",
    price: 42,
    originalPrice: null,
    rating: 4.6,
    reviews: 902,
    badge: null,
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80",
    description: "Double-walled vacuum insulated bottle that keeps drinks cold for 24 hours or hot for 12. BPA-free and built to last.",
    features: ["24hr Cold / 12hr Hot", "BPA-Free", "500ml Capacity", "Leak-Proof Lid", "Powder Coat Finish"],
  },
  {
    id: 10,
    name: "Mechanical Keyboard",
    category: "Electronics",
    price: 189,
    originalPrice: 220,
    rating: 4.8,
    reviews: 431,
    badge: "Sale",
    image: "https://store.hp.com/app/assets/images/uploads/prod/are-mechanical-keyboards-better-gaming-hero1537748638452.jpg",
    description: "Compact 75% layout mechanical keyboard with PBT keycaps and programmable RGB. Perfect for coders and writers alike.",
    features: ["Cherry MX Red Switches", "PBT Double-Shot Keycaps", "Per-Key RGB", "USB-C Detachable Cable", "Programmable via Software"],
  },
  {
    id: 11,
    name: "Linen Throw Blanket",
    category: "Home & Kitchen",
    price: 75,
    originalPrice: null,
    rating: 4.7,
    reviews: 184,
    badge: "New",
    image: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600&q=80",
    description: "Woven from 100% European flax linen, this throw blanket gets softer with every wash. A timeless addition to any living space.",
    features: ["100% European Flax Linen", "Machine Washable", "130cm × 170cm", "Fringed Edges", "OEKO-TEX Certified"],
  },
  {
    id: 12,
    name: "Running Sneakers Pro",
    category: "Clothing",
    price: 165,
    originalPrice: 195,
    rating: 4.5,
    reviews: 688,
    badge: "Sale",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80",
    description: "Engineered mesh upper with responsive foam cushioning for an effortless run. Designed for road and light trail.",
    features: ["Engineered Mesh Upper", "Responsive Foam Midsole", "Rubber Outsole", "Reflective Details", "Breathable Lining"],
  },
  {
    id: 13,
    name: "Polarized Sunglasses",
    category: "Accessories",
    price: 119,
    originalPrice: null,
    rating: 4.6,
    reviews: 303,
    badge: null,
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&q=80",
    description: "Italian acetate frames with polarized UV400 lenses. Classic aviator silhouette that never goes out of style.",
    features: ["Polarized UV400 Lenses", "Italian Acetate Frame", "Spring Hinges", "Microfiber Pouch & Case", "Lightweight 28g"],
  },
  {
    id: 14,
    name: "Smart Fitness Tracker",
    category: "Electronics",
    price: 199,
    originalPrice: null,
    rating: 4.7,
    reviews: 871,
    badge: "Hot",
    image: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&q=80",
    description: "Track your health 24/7 with heart rate monitoring, sleep tracking, GPS, and 7-day battery life in a sleek design.",
    features: ["24/7 Heart Rate Monitor", "Built-in GPS", "Sleep Tracking", "7-Day Battery Life", "5ATM Water Resistance"],
  },
  {
    id: 15,
    name: "Hardcover Journal",
    category: "Accessories",
    price: 38,
    originalPrice: null,
    rating: 4.8,
    reviews: 524,
    badge: null,
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&q=80",
    description: "A5 dotted hardcover journal with 240 pages of 120gsm paper. Lay-flat binding for smooth, uninterrupted writing.",
    features: ["240 Pages, 120gsm Paper", "A5 Format", "Lay-Flat Binding", "Dotted Grid", "Elastic Band Closure"],
  },
  {
    id: 16,
    name: "Cast Iron Skillet",
    category: "Home & Kitchen",
    price: 68,
    originalPrice: 85,
    rating: 4.9,
    reviews: 1102,
    badge: "Limited",
    image: "https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=600&q=80",
    description: "Pre-seasoned 10-inch cast iron skillet for superior heat retention. Goes from stovetop to oven to campfire effortlessly.",
    features: ["Pre-Seasoned Surface", "Oven Safe to 260°C", "Works on All Cooktops", "10-inch Diameter", "Lifetime Guarantee"],
  },
];